### ISSUE TITLE
Duplicate platform :ios, '9.0'

### ISSUE THREAD

**Issue by ikmalsuzali** [Notalib/nativescript-webview-ext#24] opened 2019-03-19 14:04 UTC
use_frameworks!
 
...

 Begin Podfile - /Users/iki/htdocs/app_v2/node_modules/nativescript-http-formdata/platforms/ios/Podfile
pod 'OMGHTTPURLRQ', '~> 3.2.4'
End Podfile

Begin Podfile - /Users/iki/htdocs/app_v2/node_modules/nativescript-floatingactionbutton/platforms/ios/Podfile
pod 'MNFloatingActionButton', '~> 2.0'

End Podfile

 Begin Podfile - /Users/iki/htdocs/app_v2/node_modules/nativescript-downloader/platforms/ios/Podfile
pod 'AFNetworking', '~> 3.0'
 End Podfile

 Begin Podfile - /Users/iki/htdocs/app_v2/node_modules/@nota/nativescript-webview-ext/platforms/ios/Podfile
platform :ios, '9.0'

pod "NotaWebViewExt", :path => "/Users/iki/htdocs/app_v2/node_modules/@nota/nativescript-webview-ext/platforms/ios/NotaWebViewExt/"

 End Podfile
end

**Comment by ddfreiling** [comment] 2019-03-19 15:34
Hello, you haven't really described what the issue is. Should we remove the `platform :ios, '9.0'` part in our Podfile?

**Comment by DanielDent** [comment] 2019-03-21 07:43
This change is resolved by NativeScript CLI 5.2.1 - see https://github.com/NativeScript/nativescript-cli/issues/3604

**Comment by m-abs** [comment] 2019-03-21 20:16
Thank you for the update.

I'll close this issue.

**Closed by m-abs** 2019-03-21 20:16 UTC
