### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by nnuvo** [Notalib/nativescript-webview-ext#17] opened 2018-12-15 21:33 UTC
Plugin is crashing after tns install.
Vue, IOS 11.4 Emulator.

**Comment by m-abs** [comment] 2018-12-17 15:55
Hi @nnuvo 

I'd really like to solve this issue, #14 reported something similar with angular but i can't reproduce it.

Could you provide an example project?

I'd also like to know which version of `xcode`, `tns-core-module`, `tns-ios` and `node` you're using.

**Comment by m-abs** [comment] 2019-01-10 14:10
I'm closing this issue.

It might have caused by difference in xcode versions, this problem should be solved by 5.0.0.

**Closed by m-abs** 2019-01-10 14:10 UTC
