### ISSUE TITLE
can't install on ios

### ISSUE THREAD

**Issue by peppeg85** [Notalib/nativescript-webview-ext#20] opened 2019-01-15 16:17 UTC
hello, i have updated at the latest version of the plugin, but now i can't run the app, i have the following error 👍 
                   #  # Begin Podfile - 
                                       
    /Users/macbook/WebstormProjects/xxxxx/node_modules/@nota/nativescript-webview- 
                           ext/platforms/ios/Podfile
                         >  platform :ios, '9.0'

how can i solve this? i have xcode 10.1, tns-ios 5.0.0 thank you

**Comment by m-abs** [comment] 2019-01-16 15:17
Hi @peppeg85 

Thank you for the bug rapport.

I'm unable to reproduce this issue.

Can you provide more of the output and maybe the content of `/Users/macbook/WebstormProjects/xxxxx/node_modules/@nota/nativescript-webview-ext/platforms/ios/Podfile`?

The `Podfile` is generated in our postinstall-script, and that might cause the problem.

Note:
I've just published v5.0.2.
It replaces the postinstall-script with a javascript-implementation.
I doubt this solves the problem, but just to be sure.

**Comment by peppeg85** [comment] 2019-01-16 16:16
hello, to solve the issue had to go back to the 0.5.0 version, but to make it work i had to clone the project again.

with the version 5.0.2 i can build, but the app crashes when i load the view that uses the webview, this is the output:

JavaScript error:
undefined:7:68: JS ERROR TypeError: undefined is not an object (evaluating 'b.prototype')
*** JavaScript call stack:
(
0   UIApplicationMain@[native code]
1   start@file:///app/tns_modules/tns-core-modules/application/application.js:272:26
2   anonymous@file:///app/app.js:50:22
3   evaluate@[native code]
4   moduleEvaluation@:1:11
5   promiseReactionJob@:1:11
)
*** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: TypeError: undefined is not an object (evaluating 'b.prototype')
at
1   @undefined:7:68
2   __extends@[native code]
3   @file:///app/tns_modules/@nota/nativescript-webview-ext/webview-ext-common.js:61:14
4   anonymous@file:///app/tns_modules/@nota/nativescript-webview-ext/webview-ext-common.js:666:2
5   evaluate@[native code]
6   moduleEvaluation@[native code]
7   promiseReactionJob@[native code]
8   require@[native code]
9   anonymous@file:///app/tns_modules/@nota/nativescript-webview-ext/webview-ext.js:8:35
10  evaluate@[native code]
11  moduleEvaluation@[native code]
12  promiseReactionJob@[native code]
13  require@[native code]
14  anonymous@file:///app/views/news/newsDetails/newsDetails.js:4:25
15  evaluate@[native code]
16  moduleEvaluation@[native code]
17  promiseReactionJob@[native code]
18  require@[native code]
19  _loop_1@file:///app/tns_modules/tns-core-modules/globals/globals.js:60:30
20  loadModule<\M-b\M^@\M-&>

**Comment by m-abs** [comment] 2019-03-11 20:48
From your other issue, I assume we can close this one.

**Closed by m-abs** 2019-03-11 20:48 UTC
